// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjJGHz9Wa0ivdhrJeXuXYeV81f0TzaiVc',
    appId: '1:588874999889:web:3df23c9537e32d83cc3070',
    messagingSenderId: '588874999889',
    projectId: 'petcareapp-1af6b',
    authDomain: 'petcareapp-1af6b.firebaseapp.com',
    storageBucket: 'petcareapp-1af6b.firebasestorage.app',
    measurementId: 'G-MPPWE54GLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNFDoMMioxaPqKzkL8-M90YCPdzjJHiE',
    appId: '1:588874999889:android:1319776eb0d0d135cc3070',
    messagingSenderId: '588874999889',
    projectId: 'petcareapp-1af6b',
    storageBucket: 'petcareapp-1af6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaMI4pD18_4zJ4lbddLYpwP5W4aVR6IWo',
    appId: '1:588874999889:ios:03d423a11ca6644bcc3070',
    messagingSenderId: '588874999889',
    projectId: 'petcareapp-1af6b',
    storageBucket: 'petcareapp-1af6b.firebasestorage.app',
    iosBundleId: 'com.example.pethug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaMI4pD18_4zJ4lbddLYpwP5W4aVR6IWo',
    appId: '1:588874999889:ios:03d423a11ca6644bcc3070',
    messagingSenderId: '588874999889',
    projectId: 'petcareapp-1af6b',
    storageBucket: 'petcareapp-1af6b.firebasestorage.app',
    iosBundleId: 'com.example.pethug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjJGHz9Wa0ivdhrJeXuXYeV81f0TzaiVc',
    appId: '1:588874999889:web:64c523424bd8ffd8cc3070',
    messagingSenderId: '588874999889',
    projectId: 'petcareapp-1af6b',
    authDomain: 'petcareapp-1af6b.firebaseapp.com',
    storageBucket: 'petcareapp-1af6b.firebasestorage.app',
    measurementId: 'G-4R758BZBGN',
  );
}
